print('Student Details')
Name = input('What is Your Name? ')
print('Hello ' + Name)
From = input('Where are You from? ')
print('hmm hmm ok')
Course = input('So, Which course would you like to Enroll in? ')
print('Sure')
About_us = input('And How do you get to know about us? ')
print('Oh ' + About_us + ' thats nice ' + 'Thank you ' + Name)
print('Lets Move on...')
print('So ' + Name + ' I am going to ask you some more information. So that I can update it on our database')